-- West Hollywood Dashboard Data Manager — one-time admin setup
-- Run this AFTER creating the admin user in Supabase Authentication > Users.
-- IMPORTANT: replace ADMIN_EMAIL_HERE near the bottom with the exact email address of the user you created.

begin;

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create table if not exists public.dashboard_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.dashboard_admins enable row level security;
revoke all on table public.dashboard_admins from anon, authenticated;
grant all on table public.dashboard_admins to service_role;

create or replace function private.is_dashboard_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.dashboard_admins a
    where a.user_id = (select auth.uid())
  );
$$;

revoke execute on function private.is_dashboard_admin() from public, anon;
grant execute on function private.is_dashboard_admin() to authenticated;

create table if not exists public.dashboard_import_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null default auth.uid(),
  user_email text,
  table_name text not null,
  action text not null,
  row_count integer not null default 0,
  file_name text,
  note text,
  details jsonb not null default '{}'::jsonb
);

alter table public.dashboard_import_log enable row level security;
revoke all on table public.dashboard_import_log from anon, authenticated;
grant select, insert on table public.dashboard_import_log to authenticated;
grant all on table public.dashboard_import_log to service_role;

-- Recreate these policies safely if this setup script is run again.
drop policy if exists "Dashboard admins read import log" on public.dashboard_import_log;
drop policy if exists "Dashboard admins add import log" on public.dashboard_import_log;
create policy "Dashboard admins read import log"
on public.dashboard_import_log for select to authenticated
using ((select private.is_dashboard_admin()));
create policy "Dashboard admins add import log"
on public.dashboard_import_log for insert to authenticated
with check ((select private.is_dashboard_admin()));

-- Give signed-in users the operations the admin UI may request; RLS below still blocks non-admin users.
do $$
declare
  t text;
begin
  foreach t in array array[
    'dashboard_pit_observations','dashboard_pit_counts','dashboard_hcl_monthly',
    'dashboard_hcl_heat_points','dashboard_hcl_reason_outcomes','dashboard_program_series',
    'dashboard_holloway','dashboard_metrics','dashboard_settings'
  ] loop
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);

    execute format('drop policy if exists "Dashboard admin read" on public.%I', t);
    execute format('drop policy if exists "Dashboard admin insert" on public.%I', t);
    execute format('drop policy if exists "Dashboard admin update" on public.%I', t);
    execute format('drop policy if exists "Dashboard admin delete" on public.%I', t);

    execute format('create policy "Dashboard admin read" on public.%I for select to authenticated using ((select private.is_dashboard_admin()))', t);
    execute format('create policy "Dashboard admin insert" on public.%I for insert to authenticated with check ((select private.is_dashboard_admin()))', t);
    execute format('create policy "Dashboard admin update" on public.%I for update to authenticated using ((select private.is_dashboard_admin())) with check ((select private.is_dashboard_admin()))', t);
    execute format('create policy "Dashboard admin delete" on public.%I for delete to authenticated using ((select private.is_dashboard_admin()))', t);
  end loop;
end $$;

-- Identity sequences used by dashboard tables/import log.
do $$
declare
  s record;
begin
  for s in
    select sequence_schema, sequence_name
    from information_schema.sequences
    where sequence_schema = 'public'
      and sequence_name ~ '^dashboard_.*'
  loop
    execute format('grant usage, select on sequence %I.%I to authenticated', s.sequence_schema, s.sequence_name);
  end loop;
end $$;

-- ADD THE ADMIN USER TO THE ALLOWLIST.
-- 1) Create the user first in Authentication > Users.
-- 2) Replace ADMIN_EMAIL_HERE below with that exact email address.
insert into public.dashboard_admins (user_id, email)
select id, email
from auth.users
where lower(email) = lower('fgomez@weho.org')
on conflict (user_id) do update set email = excluded.email;

commit;

-- Verification: this should return the admin account you added.
select user_id, email, created_at from public.dashboard_admins order by created_at;
