(() => {
'use strict';
const CFG = window.DATA_MANAGER_CONFIG || {};
const state = { session:null, datasetKey:null, mode:'upload', sourceRows:[], sourceHeaders:[], mapping:{}, prepared:[], validation:null, fileName:null };

const DATASETS = {
  pit_observations:{group:'Unsheltered counts',label:'PIT Locations',table:'dashboard_pit_observations',description:'Individual observed locations used by the PIT map. Best for CSV/Excel bulk uploads.',partitionField:'period_label',identity:'id',defaultMode:'replace',fields:[
    F('latitude','Latitude','number',true,['lat']),F('longitude','Longitude','number',true,['lng','lon','long']),F('people_count','People count','integer',true,['people','count','individuals']),F('location_label','Location label','string',false,['location','intersection','place']),F('period_label','Period label','string',true,['period','month','quarter']),F('observation_year','Observation year','integer',true,['year']),F('observation_month','Observation month','integer',true,['month number','month_num']),F('is_public','Public','boolean',false,['published'],true)
  ],example:{latitude:34.09075,longitude:-118.355484,people_count:1,location_label:'Curson and Santa Monica',period_label:'Aug 2026',observation_year:2026,observation_month:8,is_public:true}},
  pit_counts:{group:'Unsheltered counts',label:'PIT Counts',table:'dashboard_pit_counts',description:'Monthly, quarterly, and annual-average PIT count values.',conflict:['period_key'],defaultMode:'upsert',fields:[
    F('period_type','Period type','enum',true,[],null,['month','quarter','year_average']),F('period_key','Period key','string',true,['key']),F('period_label','Period label','string',true,['label']),F('value','Value','number',false,['count','average']),F('metadata','Metadata','json-object',false,[],{}),F('sort_order','Sort order','integer',true,['order']),F('is_public','Public','boolean',false,['published'],true)
  ],example:{period_type:'quarter',period_key:'2026-Q3',period_label:'Q3',value:61,metadata:'{"span":"Jul–Sep 2026","date":"Jul 23, 2026"}',sort_order:203,is_public:true}},
  hcl_monthly:{group:'Homeless Concern Line',label:'HCL Monthly',table:'dashboard_hcl_monthly',description:'Monthly Concern Line totals and chart arrays. Arrays may be JSON or comma-separated numbers.',conflict:['period_label'],defaultMode:'upsert',fields:[
    F('period_label','Period label','string',true,['month']),F('sort_order','Sort order','integer',true,['order']),F('total','Total requests','integer',true,['requests','total requests']),F('days','Days covered','integer',true,['days in period']),F('reasons','Reasons [7]','json-array',true,[],null,null,7),F('outcomes','Outcomes [4]','json-array',true,[],null,null,4),F('time_bins','Time bins [5]','json-array',true,['time bins'],null,null,5),F('day_of_week','Day of week [7]','json-array',true,['day of week','dow'],null,null,7),F('is_public','Public','boolean',false,['published'],true)
  ],example:{period_label:'Aug 2026',sort_order:14,total:250,days:31,reasons:'[120,35,40,30,10,10,5]',outcomes:'[120,45,35,50]',time_bins:'[55,60,70,60,5]',day_of_week:'[30,35,40,35,45,35,30]',is_public:true}},
  hcl_heat_points:{group:'Homeless Concern Line',label:'HCL Map Points',table:'dashboard_hcl_heat_points',description:'Geocoded Concern Line request points used by the heat map. Best for bulk upload.',partitionField:'period_label',identity:'id',defaultMode:'replace',fields:[
    F('latitude','Latitude','number',true,['lat']),F('longitude','Longitude','number',true,['lng','lon','long']),F('period_label','Period label','string',true,['month','period']),F('reason_index','Reason index','integer',true,['reason','reason code']),F('sort_order','Sort order','integer',false,['order']),F('is_public','Public','boolean',false,['published'],true)
  ],example:{latitude:34.0908,longitude:-118.3615,period_label:'Aug 2026',reason_index:0,sort_order:1,is_public:true}},
  hcl_reason_outcomes:{group:'Homeless Concern Line',label:'HCL Reason Outcomes',table:'dashboard_hcl_reason_outcomes',description:'Outcome arrays by month and reason category.',conflict:['period_label','reason_index'],defaultMode:'upsert',fields:[
    F('period_label','Period label','string',true,['month','period']),F('reason_index','Reason index','integer',true,['reason','reason code']),F('outcomes','Outcomes [4]','json-array',true,[],null,null,4),F('sort_order','Sort order','integer',false,['order']),F('is_public','Public','boolean',false,['published'],true)
  ],example:{period_label:'Aug 2026',reason_index:0,outcomes:'[70,20,15,15]',sort_order:1,is_public:true}},
  program_series:{group:'Housing & prevention',label:'Program Series',table:'dashboard_program_series',description:'Annual permanent housing, interim housing, and rental-assistance series.',conflict:['series_key','period_label'],defaultMode:'upsert',fields:[
    F('series_key','Series','enum',true,['series'],null,['permanent_housing','interim_housing','rental_households']),F('period_label','Period','string',true,['year']),F('value','Value','number',true,['count']),F('sort_order','Sort order','integer',true,['order']),F('is_public','Public','boolean',false,['published'],true)
  ],example:{series_key:'permanent_housing',period_label:'2026',value:30,sort_order:6,is_public:true}},
  holloway:{group:'Holloway',label:'Holloway Reporting',table:'dashboard_holloway',description:'Quarter/YTD Holloway summary cards. Manual entry expands the payload into easy fields.',conflict:['period_key'],defaultMode:'upsert',fields:[
    F('period_key','Period key','string',true,['quarter','key']),F('sort_order','Sort order','integer',true,['order']),F('payload','Payload','json-object',true),F('is_public','Public','boolean',false,['published'],true)
  ],payloadFields:['eyebrow','readout','servedLabel','served','servedSub','occ','occSub','occNarr','perm','permSub','part','partSub'],example:{period_key:'q4',sort_order:5,payload:'{"eyebrow":"Q4 · Jul–Sep 2026","readout":"Showing Q4 · Jul 1 – Sep 30, 2026","servedLabel":"Served during quarter","served":"31","servedSub":"Served during Q4","occ":"95.0%","occSub":"Above target","occNarr":"Holloway remained near full occupancy.","perm":"4","permSub":"Exits to permanent housing in Q4","part":"88.0%","partSub":"Goal 65%"}',is_public:true}},
  metrics:{group:'Headline metrics',label:'Dashboard Metrics',table:'dashboard_metrics',description:'Headline numbers displayed throughout the dashboard.',conflict:['metric_key'],defaultMode:'upsert',fields:[
    F('metric_key','Metric key','enum',true,['metric'],null,['people_housed_total','interim_placements_total','rental_households_total','outreach_people_of_color_pct','outreach_transgender_pct','outreach_age_50_plus_pct','hcl_median_response_time','shelter_bed_nights_year','rental_assistance_disbursed_total','rental_assistance_2026_disbursed','measure_a_households_served','measure_a_total_disbursed','measure_a_average_household']),F('value_text','Displayed value','string',true,['value']),F('is_public','Public','boolean',false,['published'],true)
  ],example:{metric_key:'people_housed_total',value_text:'440',is_public:true}},
  settings:{group:'Dashboard settings',label:'Settings',table:'dashboard_settings',description:'Small dashboard-level settings such as the public last-updated label.',conflict:['setting_key'],defaultMode:'upsert',fields:[
    F('setting_key','Setting key','enum',true,['setting'],null,['last_updated_label']),F('value_text','Value','string',true,['value']),F('is_public','Public','boolean',false,['published'],true)
  ],example:{setting_key:'last_updated_label',value_text:'August 28, 2026',is_public:true}}
};
function F(key,label,type,required=false,aliases=[],def=null,options=null,arrayLength=null){return {key,label,type,required,aliases,default:def,options,arrayLength};}

const $=id=>document.getElementById(id);
function msg(id,text,type='info'){const el=$(id);el.textContent=text;el.className='message '+type;el.classList.remove('hidden');}
function hideMsg(id){$(id).classList.add('hidden');}
function busy(text){$('busy-text').textContent=text||'Working…';$('busy').classList.remove('hidden');}
function unbusy(){$('busy').classList.add('hidden');}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalize(s){return String(s??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'');}
function configOK(){return /^https:\/\/.+\.supabase\.co$/.test(CFG.supabaseUrl||'') && /^sb_publishable_/.test(CFG.supabasePublishableKey||'');}

async function rawFetch(url,opts={}){const r=await fetch(url,opts);let body=null;const txt=await r.text();if(txt){try{body=JSON.parse(txt)}catch{body=txt}}if(!r.ok){const detail=body?.message||body?.msg||body?.error_description||body?.hint||txt||r.statusText;const e=new Error(`${r.status} ${detail}`);e.status=r.status;e.body=body;throw e}return {body,headers:r.headers,status:r.status};}
async function authFetch(path,options={}){const headers={'apikey':CFG.supabasePublishableKey,'Content-Type':'application/json',...(options.headers||{})};return rawFetch(CFG.supabaseUrl+path,{...options,headers});}
async function refreshSession(){if(!state.session?.refresh_token) return false;try{const {body}=await authFetch('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:state.session.refresh_token})});setSession(body);return true}catch{return false}}
function setSession(s){state.session=s;if(s){s.expires_at_ms=Date.now()+(Number(s.expires_in||3600)*1000);sessionStorage.setItem('weho_dm_session',JSON.stringify(s))}else sessionStorage.removeItem('weho_dm_session')}
async function ensureSession(){if(!state.session) throw new Error('Not signed in.');if(state.session.expires_at_ms-Date.now()<60000){const ok=await refreshSession();if(!ok)throw new Error('Your session expired. Please sign in again.')}return state.session}
async function restFetch(table,query='',options={}){await ensureSession();const q=query?('?'+query):'';const headers={'apikey':CFG.supabasePublishableKey,'Authorization':'Bearer '+state.session.access_token,...(options.headers||{})};if(options.body!==undefined)headers['Content-Type']='application/json';return rawFetch(`${CFG.supabaseUrl}/rest/v1/${table}${q}`,{...options,headers});}

async function signIn(email,password){const {body}=await authFetch('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});setSession(body);return body;}
async function signOut(){try{if(state.session)await authFetch('/auth/v1/logout',{method:'POST',headers:{Authorization:'Bearer '+state.session.access_token}})}catch{}setSession(null);showLogin();}
async function checkAdmin(){await restFetch('dashboard_import_log','select=id&limit=1');return true;}

function showLogin(){$('login-view').classList.remove('hidden');$('app-view').classList.add('hidden');$('user-pill').classList.add('hidden');$('logout-btn').classList.add('hidden');$('dashboard-link').classList.add('hidden');}
function showApp(){hideMsg('login-message');$('login-view').classList.add('hidden');$('app-view').classList.remove('hidden');$('logout-btn').classList.remove('hidden');$('dashboard-link').classList.remove('hidden');$('dashboard-link').href=CFG.dashboardUrl||'../';const email=state.session?.user?.email||'Signed in';$('user-pill').textContent=email;$('user-pill').classList.remove('hidden');if(!state.datasetKey)selectDataset(Object.keys(DATASETS)[0]);}

function renderNav(){const nav=$('dataset-nav');nav.innerHTML='';Object.entries(DATASETS).forEach(([key,d])=>{const b=document.createElement('button');b.type='button';b.className='dataset-btn';b.dataset.key=key;b.innerHTML=`<span class="group">${esc(d.group)}</span>${esc(d.label)}`;b.addEventListener('click',()=>selectDataset(key));nav.appendChild(b)});}
function selectDataset(key){state.datasetKey=key;state.sourceRows=[];state.prepared=[];state.validation=null;state.fileName=null;document.querySelectorAll('.dataset-btn').forEach(b=>b.classList.toggle('active',b.dataset.key===key));const d=DATASETS[key];$('dataset-group').textContent=d.group;$('dataset-title').textContent=d.label;$('dataset-desc').textContent=d.description;$('mapping-section').classList.add('hidden');$('file-meta').classList.add('hidden');$('preview-section').classList.add('hidden');$('current-section').classList.add('hidden');$('history-section').classList.add('hidden');$('file-input').value='';renderManualForm();renderWriteModes();}

function setMode(mode){state.mode=mode;document.querySelectorAll('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('upload-panel').classList.toggle('hidden',mode!=='upload');$('manual-panel').classList.toggle('hidden',mode!=='manual');$('preview-section').classList.add('hidden');}

function renderManualForm(){const d=DATASETS[state.datasetKey],form=$('manual-form');form.innerHTML='';if(d.payloadFields){d.fields.filter(f=>f.key!=='payload').forEach(f=>form.appendChild(makeInput(f,d.example[f.key])));d.payloadFields.forEach(k=>form.appendChild(makeInput({key:'payload.'+k,label:friendly(k),type:'string',required:true},safePayloadExample(d.example.payload,k))));return;}d.fields.forEach(f=>form.appendChild(makeInput(f,d.example[f.key])));}
function safePayloadExample(payload,k){try{return JSON.parse(payload)[k]??''}catch{return ''}}
function friendly(k){return k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}
function makeInput(f,example){const wrap=document.createElement('label');wrap.dataset.field=f.key;if(f.type.startsWith('json'))wrap.classList.add('wide');wrap.innerHTML=`${esc(f.label)}${f.required?' <span style="color:#b42318">*</span>':''}<span class="field-help">${esc(fieldHint(f))}</span>`;let el;if(f.type==='enum'){el=document.createElement('select');el.innerHTML='<option value="">Choose…</option>'+f.options.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('');if(example!==undefined&&example!==null)el.value=String(example)}else if(f.type.startsWith('json')){el=document.createElement('textarea');el.value=typeof example==='string'?example:JSON.stringify(example??(f.type==='json-array'?[]:{}))}else if(f.type==='boolean'){el=document.createElement('select');el.innerHTML='<option value="true">true</option><option value="false">false</option>';el.value=String(example??true)}else{el=document.createElement('input');el.type=(f.type==='number'||f.type==='integer')?'number':'text';if(f.type==='number')el.step='any';el.value=example??''}el.name=f.key;wrap.appendChild(el);return wrap;}
function fieldHint(f){if(f.type==='json-array')return f.arrayLength?`JSON or comma-separated · ${f.arrayLength} values`:'JSON or comma-separated';if(f.type==='json-object')return 'JSON object';if(f.default!==null&&f.default!==undefined)return `Default: ${typeof f.default==='object'?JSON.stringify(f.default):f.default}`;return f.type;}

function renderWriteModes(){const d=DATASETS[state.datasetKey],sel=$('write-mode');const opts=[];if(d.conflict)opts.push(['upsert','Update matching rows / add new']);opts.push(['append','Append new rows']);if(d.partitionField)opts.push(['replace','Replace matching '+d.partitionField]);sel.innerHTML=opts.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('');sel.value=d.defaultMode||opts[0][0];updatePublishHelp();}
function updatePublishHelp(){const d=DATASETS[state.datasetKey],m=$('write-mode').value;let t='';if(m==='upsert')t=`Rows matching ${d.conflict.join(' + ')} are updated; new keys are inserted.`;else if(m==='replace')t=`Existing rows for every ${d.partitionField} present in this preview are deleted, then replaced by the preview rows. A best-effort backup is restored if insertion fails.`;else t='Rows are inserted as new records. Use carefully on tables without unique keys.';$('publish-help').textContent=t;}

function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}}row.push(cell);if(row.some(x=>x!==''))rows.push(row);if(!rows.length)return[];const headers=rows[0].map(h=>String(h).trim());return rows.slice(1).filter(r=>r.some(x=>String(x).trim()!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
async function parseFile(file){const ext=(file.name.split('.').pop()||'').toLowerCase();if(ext==='csv'){return parseCSV(await file.text())}if(!window.XLSX)throw new Error('Excel support did not load. Save the file as CSV or check internet access to cdn.sheetjs.com.');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:false});const ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});}
function autoMap(headers,fields){const byNorm=new Map(headers.map(h=>[normalize(h),h]));const m={};fields.forEach(f=>{const names=[f.key,f.label,...(f.aliases||[])].map(normalize);m[f.key]=names.map(n=>byNorm.get(n)).find(Boolean)||''});return m;}
function renderMapping(){const d=DATASETS[state.datasetKey];state.sourceHeaders=state.sourceRows.length?Object.keys(state.sourceRows[0]):[];state.mapping=autoMap(state.sourceHeaders,d.fields);const grid=$('mapping-grid');grid.innerHTML='';d.fields.forEach(f=>{const div=document.createElement('div');div.className='mapping-item';const opts=['<option value="">— default / blank —</option>',...state.sourceHeaders.map(h=>`<option value="${esc(h)}" ${state.mapping[f.key]===h?'selected':''}>${esc(h)}</option>`)].join('');div.innerHTML=`<label>${esc(f.label)}${f.required?' <span class="required">*</span>':''}<span class="field-help">${esc(fieldHint(f))}</span><select data-target="${esc(f.key)}">${opts}</select></label>`;div.querySelector('select').addEventListener('change',e=>state.mapping[f.key]=e.target.value);grid.appendChild(div)});$('mapping-status').textContent=`${state.sourceHeaders.length} source columns`;$('mapping-status').className='status-chip neutral';$('mapping-section').classList.remove('hidden');}

function coerce(raw,f,rowIndex){let v=raw;if((v===undefined||v===null||String(v).trim()==='') && f.default!==null&&f.default!==undefined)v=typeof f.default==='object'?structuredClone(f.default):f.default;if(v===undefined||v===null||String(v).trim()===''){if(f.required)throw new Error(`${f.label} is required`);return null}if(f.type==='string'||f.type==='enum')return String(v).trim();if(f.type==='number'){const n=Number(String(v).replace(/,/g,''));if(!Number.isFinite(n))throw new Error(`${f.label} must be a number`);return n}if(f.type==='integer'){const n=Number(String(v).replace(/,/g,''));if(!Number.isInteger(n))throw new Error(`${f.label} must be a whole number`);return n}if(f.type==='boolean'){if(typeof v==='boolean')return v;const s=String(v).trim().toLowerCase();if(['true','1','yes','y'].includes(s))return true;if(['false','0','no','n'].includes(s))return false;throw new Error(`${f.label} must be true/false`)}if(f.type==='json-array'){let a;if(Array.isArray(v))a=v;else{const s=String(v).trim();try{a=JSON.parse(s)}catch{a=s.split(/[|,;]/).map(x=>x.trim()).filter(Boolean).map(Number)}}if(!Array.isArray(a)||a.some(x=>!Number.isFinite(Number(x))))throw new Error(`${f.label} must be a numeric array`);a=a.map(Number);if(f.arrayLength&&a.length!==f.arrayLength)throw new Error(`${f.label} must contain ${f.arrayLength} values`);return a}if(f.type==='json-object'){if(typeof v==='object'&&!Array.isArray(v))return v;try{const o=JSON.parse(String(v));if(!o||Array.isArray(o)||typeof o!=='object')throw 0;return o}catch{throw new Error(`${f.label} must be valid JSON object`)}}return v;}
function rowChecks(obj,d){const e=[],w=[];if('latitude'in obj&&(obj.latitude<-90||obj.latitude>90))e.push('Latitude outside -90 to 90');if('longitude'in obj&&(obj.longitude<-180||obj.longitude>180))e.push('Longitude outside -180 to 180');if('observation_month'in obj&&(obj.observation_month<1||obj.observation_month>12))e.push('Observation month must be 1–12');if('people_count'in obj&&obj.people_count<0)e.push('People count cannot be negative');if(d===DATASETS.hcl_monthly){for(const k of ['reasons','outcomes'])if(Array.isArray(obj[k])){const s=obj[k].reduce((a,b)=>a+Number(b||0),0);if(Number(obj.total)!==s)w.push(`${k} sum (${s}) does not equal total (${obj.total})`)}}if(d===DATASETS.hcl_heat_points&&(obj.reason_index<0||obj.reason_index>6))w.push('Reason index is usually 0–6');return {e,w};}
function prepareFromUpload(){const d=DATASETS[state.datasetKey],out=[],errors=[],warnings=[];state.sourceRows.forEach((src,i)=>{const o={};let ok=true;d.fields.forEach(f=>{try{o[f.key]=coerce(state.mapping[f.key]?src[state.mapping[f.key]]:undefined,f,i)}catch(err){errors.push(`Row ${i+2}: ${err.message}`);ok=false}});if(o.sort_order==null&&d.fields.some(f=>f.key==='sort_order'))o.sort_order=i+1;const c=rowChecks(o,d);c.e.forEach(x=>{errors.push(`Row ${i+2}: ${x}`);ok=false});c.w.forEach(x=>warnings.push(`Row ${i+2}: ${x}`));out.push({...o,__valid:ok})});return finalizeValidation(out,errors,warnings);}
function prepareManual(){const d=DATASETS[state.datasetKey],o={},errors=[],warnings=[];if(d.payloadFields){const payload={};d.fields.filter(f=>f.key!=='payload').forEach(f=>{const el=document.querySelector(`[name="${CSS.escape(f.key)}"]`);try{o[f.key]=coerce(el?.value,f,1)}catch(err){errors.push(err.message)}});d.payloadFields.forEach(k=>{payload[k]=document.querySelector(`[name="payload.${CSS.escape(k)}"]`)?.value??'';if(!String(payload[k]).trim())errors.push(`${friendly(k)} is required`)});o.payload=payload;}else d.fields.forEach(f=>{const el=document.querySelector(`[name="${CSS.escape(f.key)}"]`);try{o[f.key]=coerce(el?.value,f,1)}catch(err){errors.push(err.message)}});const c=rowChecks(o,d);errors.push(...c.e);warnings.push(...c.w);return finalizeValidation([{...o,__valid:errors.length===0}],errors,warnings);}
function finalizeValidation(rows,errors,warnings){state.prepared=rows;state.validation={errors,warnings,valid:rows.filter(r=>r.__valid).length,total:rows.length};renderPreview();return state.validation;}
function cleanRow(r,d){const o={};d.fields.forEach(f=>{if(r[f.key]!==undefined)o[f.key]=r[f.key]});return o;}

function renderPreview(){const d=DATASETS[state.datasetKey],v=state.validation;$('preview-section').classList.remove('hidden');$('preview-summary').textContent=`${v.total} row${v.total===1?'':'s'} prepared · ${v.valid} valid`;$('validation-badges').innerHTML=`<span class="badge ${v.errors.length?'bad':'good'}">${v.errors.length} errors</span><span class="badge ${v.warnings.length?'warn':'neutral'}">${v.warnings.length} warnings</span>`;const list=$('validation-list');list.innerHTML='';[...v.errors.slice(0,12).map(x=>['error',x]),...v.warnings.slice(0,8).map(x=>['warning',x])].forEach(([c,t])=>{const el=document.createElement('div');el.className='validation-item '+c;el.textContent=t;list.appendChild(el)});if(v.errors.length>12||v.warnings.length>8){const el=document.createElement('div');el.className='validation-item warning';el.textContent='Additional issues are not shown here. Correct the source file and validate again.';list.appendChild(el)};renderTable($('preview-table'),state.prepared.slice(0,50),d.fields.map(f=>f.key),true);$('publish-btn').disabled=v.errors.length>0||v.total===0;updatePublishHelp();}
function renderTable(table,rows,cols,markInvalid=false){if(!rows.length){table.innerHTML='<tbody><tr><td>No rows</td></tr></tbody>';return}table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>`<tr class="${markInvalid&&r.__valid===false?'invalid':''}">${cols.map(c=>`<td>${esc(typeof r[c]==='object'?JSON.stringify(r[c]):r[c])}</td>`).join('')}</tr>`).join('')+'</tbody>';}

function csvValue(v){if(typeof v==='object')v=JSON.stringify(v);const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function downloadTemplate(){const d=DATASETS[state.datasetKey],heads=d.fields.map(f=>f.key),row=heads.map(k=>csvValue(d.example[k]??''));downloadText(`${state.datasetKey}_template.csv`,heads.join(',')+'\n'+row.join(',')+'\n','text/csv');}
function downloadText(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},100);}

async function publish(){const d=DATASETS[state.datasetKey],mode=$('write-mode').value,rows=state.prepared.filter(r=>r.__valid).map(r=>cleanRow(r,d));if(!rows.length)return;if(state.validation?.errors?.length)return;let detail='';if(mode==='replace'){const vals=[...new Set(rows.map(r=>r[d.partitionField]))];detail=` This will replace ${d.partitionField}: ${vals.join(', ')}.`}if(!confirm(`Publish ${rows.length} row(s) to ${d.label}?${detail}`))return;busy('Publishing data…');try{let affected=0;if(mode==='upsert'){affected=await insertChunks(d,rows,true)}else if(mode==='append'){affected=await insertChunks(d,rows,false)}else if(mode==='replace'){affected=await replacePartitions(d,rows)}await logImport(d,mode,affected);msg('global-message',`Published ${affected} row${affected===1?'':'s'} to ${d.label}. Refresh the public dashboard to see the change.`,'success');$('preview-section').classList.add('hidden');if(state.mode==='manual')renderManualForm();else clearFile();}catch(err){msg('global-message','Publish failed: '+err.message,'error')}finally{unbusy();}}
async function insertChunks(d,rows,upsert){let count=0;for(let i=0;i<rows.length;i+=500){const chunk=rows.slice(i,i+500),q=upsert&&d.conflict?'on_conflict='+encodeURIComponent(d.conflict.join(',')):'';const prefer=upsert?'resolution=merge-duplicates,return=representation':'return=representation';const {body}=await restFetch(d.table,q,{method:'POST',headers:{Prefer:prefer},body:JSON.stringify(chunk)});count+=Array.isArray(body)?body.length:chunk.length}return count;}
async function selectPartition(d,val){const q=`select=*&${encodeURIComponent(d.partitionField)}=eq.${encodeURIComponent(val)}`;const {body}=await restFetch(d.table,q);return Array.isArray(body)?body:[];}
async function deletePartition(d,val){const q=`${encodeURIComponent(d.partitionField)}=eq.${encodeURIComponent(val)}`;const {body}=await restFetch(d.table,q,{method:'DELETE',headers:{Prefer:'return=representation'}});return Array.isArray(body)?body.length:0;}
function stripIdentity(rows,d){return rows.map(r=>{const o={...r};if(d.identity)delete o[d.identity];return o});}
async function replacePartitions(d,rows){const vals=[...new Set(rows.map(r=>r[d.partitionField]))],backups=[];for(const v of vals)backups.push(...await selectPartition(d,v));try{for(const v of vals)await deletePartition(d,v);return await insertChunks(d,rows,false)}catch(err){try{for(const v of vals)await deletePartition(d,v);if(backups.length)await insertChunks(d,stripIdentity(backups,d),false)}catch{}throw new Error(err.message+' Previous rows were backed up and a restore was attempted.');}}
async function logImport(d,action,count){try{await restFetch('dashboard_import_log','',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{user_email:state.session?.user?.email||null,table_name:d.table,action,row_count:count,file_name:state.fileName,note:$('import-note').value.trim()||null,details:{dataset:state.datasetKey}}])})}catch(e){console.warn('Import log failed',e)}}

async function loadCurrent(){const d=DATASETS[state.datasetKey];busy('Loading current rows…');try{const order=d.fields.some(f=>f.key==='sort_order')?'&order=sort_order.asc':'';const {body}=await restFetch(d.table,`select=*&limit=200${order}`);$('current-summary').textContent=`Showing up to 200 current rows from ${d.table}.`;$('current-section').classList.remove('hidden');$('history-section').classList.add('hidden');const cols=body.length?Object.keys(body[0]).filter(k=>k!=='id'):d.fields.map(f=>f.key);renderTable($('current-table'),body,cols)}catch(err){msg('global-message','Could not load current rows: '+err.message,'error')}finally{unbusy();}}
async function loadHistory(){busy('Loading import history…');try{const {body}=await restFetch('dashboard_import_log','select=created_at,user_email,table_name,action,row_count,file_name,note&order=created_at.desc&limit=100');$('history-section').classList.remove('hidden');$('current-section').classList.add('hidden');renderTable($('history-table'),body,['created_at','user_email','table_name','action','row_count','file_name','note'])}catch(err){msg('global-message','Could not load import history: '+err.message,'error')}finally{unbusy();}}

function clearFile(){state.sourceRows=[];state.prepared=[];state.validation=null;state.fileName=null;$('file-input').value='';$('file-meta').classList.add('hidden');$('mapping-section').classList.add('hidden');$('preview-section').classList.add('hidden');}
async function handleFile(file){if(!file)return;hideMsg('global-message');busy('Reading file…');try{const rows=await parseFile(file);if(!rows.length)throw new Error('No data rows were found in the first worksheet.');state.sourceRows=rows;state.fileName=file.name;$('file-meta').textContent=`${file.name} · ${rows.length} data rows`;$('file-meta').classList.remove('hidden');renderMapping()}catch(err){msg('global-message','Could not read file: '+err.message,'error')}finally{unbusy();}}

function bind(){renderNav();$('login-form').addEventListener('submit',async e=>{e.preventDefault();hideMsg('login-message');busy('Signing in…');try{await signIn($('email').value.trim(),$('password').value);await checkAdmin();showApp()}catch(err){if(state.session&&err.status===403){msg('login-message','Sign-in succeeded, but this account is not authorized as a dashboard administrator. Run admin_setup.sql and add this email to dashboard_admins.','error')}else msg('login-message','Sign-in failed: '+err.message,'error')}finally{unbusy()}});$('logout-btn').addEventListener('click',signOut);document.querySelectorAll('.mode-tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));const dz=$('drop-zone'),fi=$('file-input');dz.addEventListener('click',()=>fi.click());dz.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fi.click()}});['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>handleFile(e.dataTransfer.files?.[0]));fi.addEventListener('change',()=>handleFile(fi.files?.[0]));$('validate-btn').addEventListener('click',prepareFromUpload);$('clear-file-btn').addEventListener('click',clearFile);$('manual-preview-btn').addEventListener('click',prepareManual);$('manual-reset-btn').addEventListener('click',renderManualForm);$('template-btn').addEventListener('click',downloadTemplate);$('write-mode').addEventListener('change',updatePublishHelp);$('publish-btn').addEventListener('click',publish);$('current-btn').addEventListener('click',loadCurrent);$('close-current').addEventListener('click',()=>$('current-section').classList.add('hidden'));$('history-btn').addEventListener('click',loadHistory);$('close-history').addEventListener('click',()=>$('history-section').classList.add('hidden'));}

async function init(){if(!configOK()){showLogin();msg('login-message','Configuration is missing or invalid. Check config.js.','error');return}bind();try{const saved=sessionStorage.getItem('weho_dm_session');if(saved){state.session=JSON.parse(saved);await ensureSession();await checkAdmin();showApp()}else showLogin()}catch{setSession(null);showLogin()}}
init();
})();
